apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "65.1.1"
    helm:
      valuesObject:
        grafana:
          enabled: true
          adminPassword: "skillpulse@123"
          service:
            type: NodePort
            nodePort: 32000
        prometheus:
          prometheusSpec:
            retention: 7d
            resources:
              requests:
                memory: 512Mi
                cpu: 250m
              limits:
                memory: 1Gi
                cpu: 500m
        alertmanager:
          enabled: true
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      jsonPointers:
        - /status/terminatingReplicas
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /status/terminatingReplicas
    - group: ""
      kind: "Service"
      jsonPointers:
        - /status/terminatingReplicas
