apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillpulse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=heyyprakhar1/skillpulse-backend, frontend=heyyprakhar1/skillpulse-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^sha-
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^sha-
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/update-interval: 2m
spec:
  project: default
  source:
    repoURL: https://github.com/Heyyprakhar1/github-actions-kubernetes-masterclass
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: skillpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
